version: "3.3"

services:
  db:
    image: postgres:15
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - compose.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  app:
    depends_on:
      - db
    env_file:
      - compose.env
    environment:
      - POSTGRES_SERVER=db:5432
      # Allow explicit env var override for tests
    build:
      context: .

volumes:
  app-db-data:
