project_slug: {{ cookiecutter.project_slug }}
docker_image: {{ cookiecutter.docker_registry_url }}/{{ cookiecutter.docker_image_name }}
app_external_port: 8000
amplitude_token: YOUR_TOKEN
on_bot_start_message: {{cookiecutter.on_bot_start_message}}
on_bot_help_message: {{cookiecutter.on_bot_help_message}}

#{% raw %}
code_path: /home/{{ansible_user}}/{{ project_slug }}
#{% endraw %}
